#rover supergraph compose --config ./supergraph-config.yaml > supergraph.graphql
subgraphs:
  accounts:
    routing_url: http://localhost:4001/accounts
    schema:
      subgraph_url: http://localhost:4001/accounts
  products:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
  reviews:
    routing_url: http://localhost:4003/
    schema:
      subgraph_url: http://localhost:4003/
