subgraphs:
  products:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  reviews:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
